# Generated by Django 3.1.7 on 2023-01-15 09:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_film_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='viewing',
            name='title',
        ),
        migrations.AddField(
            model_name='viewing',
            name='film',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.film'),
        ),
        migrations.AddField(
            model_name='viewing',
            name='start_time',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
    ]
