# Generated by Django 3.1.7 on 2023-01-15 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230115_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewing',
            name='duration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='run_time', to='core.film'),
        ),
    ]
