# Generated by Django 3.1.7 on 2023-01-15 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_viewing_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='title',
        ),
        migrations.AddField(
            model_name='booking',
            name='film',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.film'),
        ),
    ]
