# Generated by Django 3.1.7 on 2023-01-15 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230115_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='film',
        ),
        migrations.AddField(
            model_name='booking',
            name='viewing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.viewing'),
        ),
    ]
